#!/bin/sh

# lang
uci set luci.main.lang=auto
uci commit luci

# system settings
uci -q batch <<-EOF
    set system.@system[0].timezone=CST-8
    set system.@system[0].zonename=Asia/Shanghai

    set system.@system[0].zram_priority=100

    delete system.ntp.server
    add_list system.ntp.server="ntp.tencent.com"
    add_list system.ntp.server="ntp1.aliyun.com"
    add_list system.ntp.server="ntp.ntsc.ac.cn"
    add_list system.ntp.server="cn.pool.ntp.org"
EOF
uci commit system

# uhttpd
uci set uhttpd.main.rfc1918_filter=0
uci set uhttpd.main.redirect_https=0
uci commit uhttpd && service uhttpd reload

# dnsmasq
sed -i '/log-facility/d' /etc/dnsmasq.conf
echo "log-facility=/dev/null" >> /etc/dnsmasq.conf

# feed
sed -i 's,downloads.openwrt.org,mirror.sjtu.edu.cn/openwrt,g' /etc/opkg/distfeeds.conf

opkg flag hold luci-app-firewall
opkg flag hold firewall
opkg flag hold dnsmasq-full

# luci cache
rm -rf /tmp/luci-modulecache/
rm -f /tmp/luci-indexcache

exit 0
